// Auto-generated by scripts/generate-build-info.mjs before every build/serve — do not edit by hand.
export const BUILD_INFO = {
  commit: '0feaba8+',
  builtAt: '2026-08-17T20:58:25.184Z',
} as const;
