// Auto-generated by scripts/generate-build-info.mjs before every build/serve — do not edit by hand.
export const BUILD_INFO = {
  commit: 'e0e08b4+',
  builtAt: '2026-08-17T21:30:16.853Z',
} as const;
