// Auto-generated by scripts/generate-build-info.mjs before every build/serve — do not edit by hand.
export const BUILD_INFO = {
  commit: '336764f+',
  builtAt: '2026-08-17T21:05:17.862Z',
} as const;
